name: panel-oauth-test
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.9
  - build
  - bump2version
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  # Utilities
  - pyprojroot
  - python-dotenv
  - panel
  # CLI development
  - typer
  # Software testing
  - hypothesis
  - pytest
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
